//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaptWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyUnit()
        {
            this.Timetables = new HashSet<Timetable>();
            this.Courses = new HashSet<Cours>();
            this.Lecturers = new HashSet<Lecturer>();
        }
    
        public string UnitID { get; set; }
        public string UnitName { get; set; }
        public string UnitDescription { get; set; }
        public int UnitCredits { get; set; }
        public int UnitSemester { get; set; }
        public int UnitYear { get; set; }
        public string UnitElective { get; set; }
        public string UnitCompensatable { get; set; }
        public string UnitExam { get; set; }
        public string UnitAssignment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timetable> Timetables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturer> Lecturers { get; set; }
    }
}
